# Site settings
title: LeW Blog # 博客标题
SEOTitle: 樂的博客 | LeW Blog # 显示在浏览器上搜索的时候显示的标题
header-img: img/post-bg-css.jpg # 首页头部背景图
email: 87292008@qq.com # 邮箱地址
description: "这里是 @LeW王樂 的个人博客，与你一起发现世界。"
keyword: "王乐, 樂, LeW, 王樂的博客, LeW Blog, Java，Kotlin, 全栈"
url: "https://wangle.pub"          # your host, for absolute URL
baseurl: ""      # for example, '/blog' if your blog hosted on 'host/blog'
github_repo: "https://github.com/wllyy189/wllyy189.github.io.git" # you code repository


# Publish posts or collection documents with a future date.
future: true


# SNS settings
RSS: false
#zhihu_username:     
github_username:    wllyy189
#facebook_username:  
#twitter_username:
#jianshu_username:   




# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`



# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins: [jekyll-paginate]




# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# 评论系统

# Disqus settings
# Disqus（https://disqus.com/）
disqus_username: wangle-pub

# Gitalk settings
# gitalk:
#   enable: true #是否开启Gitalk评论
#   clientID:  #生成的clientID
#   clientSecret:  #生成的clientSecret
#   repo: wllyy189.github.io #仓库名称
#   owner: wllyy189 #github用户名
#   admin: wllyy189
#   distractionFreeMode: true #是否启用类似FB的阴影遮罩


# Netease settings
netease_comment: false


# Analytics settings
# Baidu Analytics
ba_track_id: 243af758c93fe1bb0cb285baff48a6ef
# Google Analytics
# ga_track_id: '' # Format: UA-xxxxxx-xx
# ga_domain: wangle.pub # 默认的是 auto, 这里我是自定义了的域名，你如果没有自己的域名，需要改成auto




# Sidebar settings
sidebar: true # 是否开启侧边栏                           
sidebar-avatar: /img/avatar-lew.jpg # 个人头像
sidebar-about-description: "写写代码。世界那么大，多玩玩看看。" # 个人简介




# Featured Tags
featured-tags: true # 是否使用首页标签
featured-condition-size: 1 # 相同标签数量大于这个数，才会出现在首页



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true



# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false



# Friends
friends: [
    {
        title: "LeW Blog",
        href: "https://wangle.pub"
    }
]
